### ISSUE TITLE
Scanning Costs

### ISSUE THREAD

**Issue by allwithfly** [SpectralOps/netz#2]
Hello

Please, any estimate on the cost of a single port scan on aws? I have never run a full scan because halfway through the scan I get abused by aws alerts.

thank you

**Comment by jondot** [comment]
@cmpxchg16 can you help?

**Comment by cmpxchg16** [comment]
@allwithfly Hello.
Basically, if we put aside the PF_RING ZC cost that you can scan without (more time to scan), the cost is the ec2 machine used by the ECS task, in our tests we used different types of ec2 machines, so the cost varies between the different machine types, for instance, the strongest machine we tested with is c4.8xlarge which cost 1.6$ per hour, and if a regular scan finished less than 1 hour, so this is the machine cost.
AWS doesn't charge for data ingress (free), but they do charge on the data egress (get out data back from AWS), but because most of the scan is just SYN packets which are very very small, the next cost is the egress out after the port discovery is done by `masscan`, then running the `zgrab2` protocol specific for a small portion of discovered ports is very low, in most cases few MB (depending on the number of the results in the port scan), so the main cost is the ec2 instance.
The egress cost estimated:

Up to 1 GB for Month - Free
Next 9.999 TB for Month -  $0.09 per GB

Hope it answers your question :))

**Comment by allwithfly** [comment]
@jondot  @cmpxchg16  thank you so much.
